name: Test and deploy

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Test
      run: |
        npm run test

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
